name: Deployment 1
on: push
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run the Lint
        run: npm run lint
      - name: Run the Test
        run: npm run test
      - name: Build the code
        run: npm run  build
      - name: Deploying
        run: echo "Deploying....."